name: Build and Push Docker Image

on:
  release:
    types: [published]


jobs:
  build-amd64:
    name: Build and Push Docker Image amd64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
            cat <<EOF > .env
            PORT=${{ vars.ENV_PORT }}
            DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}
            SECRET_KEY_BASE=${{ secrets.ENV_SECRET_KEY_BASE }}
            PHX_HOST=0.0.0.0${{ vars.ENV_PHX_HOST }}
            EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jeftecosta/elixircr
          tags: |
              type=semver,pattern={{version}}
              type=edge,branch=main
              type=ref,event=pr
          labels: |
              org.opencontainers.image.source=https://github.com/jeftecosta/elixircr

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./environment/production/app/Dockerfile
          platforms: linux/amd64
          tags:  ${{ steps.meta.outputs.tags }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
                
  build-arm64:
    name: Build and Push Docker Image arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
            cat <<EOF > .env
            PORT=${{ vars.ENV_PORT }}
            DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}
            SECRET_KEY_BASE=${{ secrets.ENV_SECRET_KEY_BASE }}
            PHX_HOST=0.0.0.0${{ vars.ENV_PHX_HOST }}
            EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/jeftecosta/elixircr
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=main
            type=ref,event=pr
          labels: |
            org.opencontainers.image.source=https://github.com/jeftecosta/elixircr

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./environment/production/app/Dockerfile
          platforms: linux/arm64 
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image