name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./environment/prodution/app/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/elixircr:${{ github.ref_name }}
