name: Build and Push Docker Image

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: macos-15
    # strategy:
    #   matrix:
    #     arch: [amd64, arm64, x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3

      - name: Create .env file
        run: |
            cat <<EOF > .env
            PORT=${{ vars.ENV_PORT }}
            DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}
            SECRET_KEY_BASE=${{ secrets.ENV_SECRET_KEY_BASE }}
            PHX_HOST=0.0.0.0${{ vars.ENV_PHX_HOST }}
            EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./environment/production/app/Dockerfile
          platforms: linux/amd64,linux/arm64 
          tags: ghcr.io/jeftecosta/elixircr:latest
                
